# Generated by Django 5.0.14 on 2026-02-13 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('plant_type', models.CharField(blank=True, max_length=100, verbose_name='Тип растений')),
                ('area_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь (м²)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watering_duration', models.IntegerField(default=10, verbose_name='Длительность полива (мин)')),
                ('watering_frequency', models.IntegerField(default=1, verbose_name='Частота полива (раз в день)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Зона сада',
                'verbose_name_plural': 'Зоны сада',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время измерения')),
                ('soil_moisture', models.IntegerField(blank=True, null=True, verbose_name='Влажность почвы (%)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура (°C)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='Влажность воздуха (%)')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='main.gardenzone')),
            ],
            options={
                'verbose_name': 'Показание датчика',
                'verbose_name_plural': 'Показания датчиков',
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Система онлайн')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='Последнее подключение')),
                ('water_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Давление воды')),
                ('total_water_used', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего использовано воды (л)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус системы',
                'verbose_name_plural': 'Статусы систем',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес участка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('duration', models.IntegerField(verbose_name='Длительность (мин)')),
                ('water_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Использовано воды (л)')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Ручной запуск')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.gardenzone')),
            ],
            options={
                'verbose_name': 'Запись полива',
                'verbose_name_plural': 'История полива',
            },
        ),
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время полива')),
                ('days_of_week', models.CharField(default='1,2,3,4,5,6,7', max_length=50, verbose_name='Дни недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.gardenzone')),
            ],
            options={
                'verbose_name': 'Расписание полива',
                'verbose_name_plural': 'Расписания полива',
            },
        ),
    ]
